# Generated by Django 2.1.1 on 2018-10-02 05:44

from django.db import migrations, models
import trips.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180930_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=trips.models.upload_image_path),
        ),
    ]
